
DROP 	SEQUENCE PROJECT_CREATENOSEQ;
CREATE 	SEQUENCE PROJECT_CREATENOSEQ;
DROP TABLE 	PROJECT_CREATE;

CREATE TABLE PROJECT_CREATE(
	PROJECT_CREATENO 	NUMBER 	PRIMARY KEY
	,USERNO 			NUMBER
	,PROJECTNO 			NUMBER
	,CONSTRAINT FK_USERNO 		FOREIGN KEY(USERNO) 	REFERENCES USERINFO(USERNO)
	,CONSTRAINT FK_PROJECTNO 	FOREIGN KEY(PROJECTNO) 	REFERENCES PROJECT(PROJECTNO));