--테이블 구조는 공유폴더 내 테이블정의서 or www.erdcloud.com/d/t6xePAoBokaZXd6Ym 참조
--!!!!테이블 구조 수정시 1.ERDcloud / 2.SQL문 / 3.08논리물리ERD/ 4.09테이블정의서 모두 업데이트 해줘야됌...!!
--순서.테이블이름,속성갯수

DROP TABLE TODO;
DROP TABLE TEXT;
DROP TABLE CHANNEL_CREATE;
DROP TABLE CHATTITLE;
DROP TABLE PROJECT_CREATE;
DROP TABLE USERINFO;
DROP TABLE PROJECT;
DROP TABLE MAPDB;
DROP TABLE FILEDB;
DROP TABLE CHANNEL;

--1.회원정보8
DROP SEQUENCE USERNOSEQ;
CREATE SEQUENCE USERNOSEQ;

CREATE TABLE USERINFO(
USERNO NUMBER PRIMARY KEY,
USEREMAIL VARCHAR2(50) NOT NULL,
USERPW VARCHAR2(100) NOT NULL,
USERNAME VARCHAR2(20) NOT NULL,
USERGENDER VARCHAR2(1),
USERENABLED VARCHAR2(1) NOT NULL,
USERROLE VARCHAR2(20) NOT NULL,
PROFILEURL VARCHAR2(3000),
CONSTRAINT UI_USERGENDER_CK CHECK (USERGENDER IN('M', 'W')), --gender ck
CONSTRAINT UI_USERENABLED_CK CHECK (USERENABLED IN('Y', 'N')) --enabled ck
);

--2.프로젝트3
DROP SEQUENCE PROJECTNOSEQ;
CREATE SEQUENCE PROJECTNOSEQ;

CREATE TABLE PROJECT (
PROJECTNO NUMBER PRIMARY KEY,
PROJECTNAME VARCHAR2(20) NOT NULL,
PROJECTTITLE VARCHAR2(50)
);

--3.프로젝트참여3
DROP SEQUENCE PROJECT_CREATENOSEQ;
CREATE SEQUENCE PROJECT_CREATENOSEQ;

CREATE TABLE PROJECT_CREATE(
PROJECT_CREATENO NUMBER PRIMARY KEY,
USERNO NUMBER NOT NULL,
PROJECTNO NUMBER NOT NULL,
CONSTRAINT PC_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERINFO(USERNO),	--userno FK
CONSTRAINT PC_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO) --projectno FK
);

--4.채널(채팅방)4
DROP SEQUENCE CHANNELNOSEQ;
CREATE SEQUENCE CHANNELNOSEQ;

CREATE TABLE CHANNEL(
CHANNELNO NUMBER PRIMARY KEY,
CHANNERNAME VARCHAR2(30),
CHANNELSTATUS VARCHAR2(10),
CHANNELTIME DATE
);

--5.지도3
DROP SEQUENCE MAPNOSEQ;
CREATE SEQUENCE MAPNOSEQ;

CREATE TABLE MAPDB(
MAPNO NUMBER PRIMARY KEY,
LATITUDE NUMBER NOT NULL,
LONGITUDE NUMBER NOT NULL
);

--6.파일3
DROP SEQUENCE FILENOSEQ;
CREATE SEQUENCE FILENOSEQ;

CREATE TABLE FILEDB(
FILENO NUMBER PRIMARY KEY,
FILES VARCHAR2(3000) NOT NULL, --파일 경로(url)
FILETITLE VARCHAR2(30) NOT NULL
);

--7.게시글9
DROP SEQUENCE TITLENOSEQ;
CREATE SEQUENCE TITLENOSEQ;
DROP SEQUENCE ANSWERSQSEQ;
CREATE SEQUENCE ANSWERSQSEQ;

CREATE TABLE CHATTITLE(
TITLENO NUMBER PRIMARY KEY,
USERNO NUMBER,
PROJECTNO NUMBER NOT NULL,
TITLE VARCHAR2(100),
CONTENT VARCHAR2(3000),
DELFLAG VARCHAR2(1),
REGDATE DATE NOT NULL,
MAPNO NUMBER,
FILENO NUMBER,
CONSTRAINT CT_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERINFO(USERNO),	--userno FK
CONSTRAINT CT_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO),--projectno FK
CONSTRAINT CT_DELFLAG_CK CHECK (DELFLAG IN('Y', 'N')), 				--delflag CK
CONSTRAINT CT_FK_MAPNO FOREIGN KEY(MAPNO) REFERENCES MAPDB(MAPNO) ON DELETE CASCADE, --mapno FK, 삭제시 mapdb에서도 삭제
CONSTRAINT CT_FK_FILENO FOREIGN KEY(FILENO) REFERENCES FILEDB(FILENO) ON DELETE CASCADE --fileno FK, 삭제시 filedb에서도 삭제
);

--8.채팅글8
DROP SEQUENCE TEXTNOSEQ;
CREATE SEQUENCE TEXTNOSEQ;

CREATE TABLE TEXT(
TEXTNO NUMBER PRIMARY KEY,
USERNO NUMBER NOT NULL,
CHANNELNO NUMBER NOT NULL,
ANSWERSQ NUMBER NOT NULL,
TEXTCONTENT VARCHAR2(3000),
IP VARCHAR2(50) NOT NULL,
TEXTTIME DATE NOT NULL,
MAPNO NUMBER,
FILENO NUMBER,
CONSTRAINT TT_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERINFO(USERNO), --userno FK
CONSTRAINT TT_FK_CHANNERNO FOREIGN KEY(CHANNELNO) REFERENCES CHANNEL(CHANNELNO), --channelno FK
CONSTRAINT TT_FK_MAPNO FOREIGN KEY(MAPNO) REFERENCES MAPDB(MAPNO) ON DELETE CASCADE, --mapno FK, 삭제시 mapdb에서도 삭제
CONSTRAINT TT_FK_FILENO FOREIGN KEY(FILENO) REFERENCES FILEDB(FILENO) ON DELETE CASCADE --fileno FK, 삭제시 filedb에서도 삭제
);

--9.채팅참여4
DROP SEQUENCE CHANNEL_CREATENOSEQ;
CREATE SEQUENCE CHANNEL_CREATENOSEQ;

CREATE TABLE CHANNEL_CREATE(
CHANNEL_CREATENO NUMBER PRIMARY KEY,
USERNO NUMBER NOT NULL,
CHANNELNO NUMBER NOT NULL,
PROJECTNO NUMBER NOT NULL,
CONSTRAINT CC_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERINFO(USERNO), --userno FK
CONSTRAINT CC_FK_CHANELNO FOREIGN KEY(CHANNELNO) REFERENCES CHANNEL(CHANNELNO), --channelno FK
CONSTRAINT CC_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO) --projectno FK
);

--10.일정7
DROP SEQUENCE TODOSEQ;
CREATE SEQUENCE TODOSEQ;

CREATE TABLE TODO(
TODONO NUMBER PRIMARY KEY,
PROJECTNO NUMBER NOT NULL,
USERNO NUMBER NOT NULL,
TODOTITLE VARCHAR2(4000) NOT NULL,
TODOCONTENT VARCHAR2(4000),
TODODATE VARCHAR2(12),
TODOREGDATE DATE NOT NULL,
CONSTRAINT TD_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERINFO(USERNO), --userno FK
CONSTRAINT TD_FK_PROJECTNO FOREIGN KEY(PROJECTNO) REFERENCES PROJECT(PROJECTNO) --projectno FK
);


--테스트용 INSERT 구문들. 테스트 데이터가 필요시 넣으면 된다.
--시퀀스는 잘못 실행시 2 이후의 번호로 시작되므로 유의.
--FK유의. 만일 일부구문만 사용할 생각이라면 
--다른 테이블에 선행 입력되어야 하는 데이터를 파악 후 사용하자.

--프로젝트
INSERT INTO PROJECT(PROJECTNO ,PROJECTNAME ,PROJECTTITLE )
VALUES(PROJECTNOSEQ.NEXTVAL,'expjname','expjtitle');
--유저정보
INSERT INTO USERINFO(USERNO,USEREMAIL ,USERPW ,USERNAME ,USERGENDER ,USERENABLED ,USERROLE ,PROFILEURL)
VALUES( USERNOSEQ.NEXTVAL ,'ex@ex.com','expw' ,'exname', 'M','Y','ADMIN', 1);
--프로젝트참여
INSERT INTO PROJECT_CREATE(PROJECT_CREATENO ,USERNO ,PROJECTNO)
VALUES (PROJECT_CREATENOSEQ.NEXTVAL , 1, 1);
--채널
INSERT INTO CHANNEL(CHANNELNO, CHANNERNAME, CHANNELSTATUS, CHANNELTIME)
VALUES(CHANNELNOSEQ.NEXTVAL , 'exchname','exchstatus','20190117');
--지도
INSERT INTO MAPDB(MAPNO, LATITUDE, LONGITUDE)
VALUES(MAPNOSEQ.NEXTVAL, 192, 192);
--파일
INSERT INTO FILEDB(FILENO, FILES, FILETITLE)
VALUES(FILENOSEQ.NEXTVAL, 'c://notexist.jpg','exfltitle');
--게시글
INSERT INTO CHATTITLE( TITLENO, USERNO, PROJECTNO, TITLE, CONTENT,
DELFLAG, REGDATE, MAPNO, FILENO)
VALUES(TITLENOSEQ.NEXTVAL, 1, 1, 'excttitle', 'exctcontent',
'N','20190117',1,1);